name = "words"
main = "index.ts"
compatibility_date = "2024-05-24"

[ai]
binding = "AI"
remote = true

[[d1_databases]]
binding = "DB"
database_name = "quote-db"
# database_id = "quote-db" # Local / Placeholder dev database ID
database_id = "f01db144-0483-4eb5-ba85-247509c8648c"

[[vectorize]]
binding = "VECTORIZE"
index_name = "quote-index"
remote = true
